<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LivroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //id	titulo	autor	genero_id	quantidade_disponivel	acao	responsavel_mov	created_at	updated_at	
        DB::table('livro')->insert([
            [
                'titulo' => 'O Senhor dos Anéis',
                'autor' => 'J.R.R. Tolkien',
                'genero_id' => 3,
                'descricao_livro' => 'Um épico de fantasia que narra a jornada para destruir o Anel do Poder.',
                'quantidade_disponivel' => 5,
                'acao' => 'adicionou',
                'responsavel_mov' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Dom Casmurro',
                'autor' => 'Machado de Assis',
                'genero_id' => 2,
                'descricao_livro' => 'Um clássico da literatura brasileira sobre ciúme e memória.',
                'quantidade_disponivel' => 4,
                'acao' => 'editou',
                'responsavel_mov' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => '1984',
                'autor' => 'George Orwell',
                'genero_id' => 1,
                'descricao_livro' => 'Uma distopia que critica regimes totalitários e o controle governamental.',
                'quantidade_disponivel' => 7,
                'acao' => 'removeu',
                'responsavel_mov' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Código Da Vinci',
                'autor' => 'Dan Brown',
                'genero_id' => 4,
                'descricao_livro' => 'Um thriller de mistério envolvendo símbolos e segredos antigos.',
                'quantidade_disponivel' => 6,
                'acao' => 'adicionou',
                'responsavel_mov' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'A Guerra dos Tronos',
                'autor' => 'George R.R. Martin',
                'genero_id' => 3,
                'descricao_livro' => 'Intrigas políticas e batalhas em um mundo de fantasia medieval.',
                'quantidade_disponivel' => 3,
                'acao' => 'removeu',
                'responsavel_mov' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Pequeno Príncipe',
                'autor' => 'Antoine de Saint-Exupéry',
                'genero_id' => 1,
                'descricao_livro' => 'Uma fábula poética sobre amizade e a essência da vida.',
                'quantidade_disponivel' => 8,
                'acao' => 'editou',
                'responsavel_mov' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Orgulho e Preconceito',
                'autor' => 'Jane Austen',
                'genero_id' => 2,
                'descricao_livro' => 'Um romance clássico sobre amor, classe social e mal-entendidos.',
                'quantidade_disponivel' => 5,
                'acao' => 'adicionou',
                'responsavel_mov' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'A Menina que Roubava Livros',
                'autor' => 'Markus Zusak',
                'genero_id' => 4,
                'descricao_livro' => 'História emocionante sobre a vida durante a Segunda Guerra Mundial.',
                'quantidade_disponivel' => 6,
                'acao' => 'removeu',
                'responsavel_mov' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Sapiens',
                'autor' => 'Yuval Noah Harari',
                'genero_id' => 8,
                'descricao_livro' => 'Uma breve história da humanidade, desde os primeiros humanos até hoje.',
                'quantidade_disponivel' => 9,
                'acao' => 'adicionou',
                'responsavel_mov' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Diário de Anne Frank',
                'autor' => 'Anne Frank',
                'genero_id' => 6,
                'descricao_livro' => 'Relatos pessoais de uma menina judia escondida durante a guerra.',
                'quantidade_disponivel' => 4,
                'acao' => 'editou',
                'responsavel_mov' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Como Fazer Amigos e Influenciar Pessoas',
                'autor' => 'Dale Carnegie',
                'genero_id' => 7,
                'descricao_livro' => 'Dicas de comunicação e relacionamento interpessoal para sucesso pessoal.',
                'quantidade_disponivel' => 10,
                'acao' => 'removeu',
                'responsavel_mov' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Universo numa Casca de Noz',
                'autor' => 'Stephen Hawking',
                'genero_id' => 8,
                'descricao_livro' => 'Explicações acessíveis sobre os mistérios do universo.',
                'quantidade_disponivel' => 5,
                'acao' => 'adicionou',
                'responsavel_mov' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Cem Anos de Solidão',
                'autor' => 'Gabriel García Márquez',
                'genero_id' => 1,
                'descricao_livro' => 'Saga da família Buendía em uma cidade fictícia da América Latina.',
                'quantidade_disponivel' => 6,
                'acao' => 'removeu',
                'responsavel_mov' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Hobbit',
                'autor' => 'J.R.R. Tolkien',
                'genero_id' => 3,
                'descricao_livro' => 'Aventura de Bilbo Bolseiro antes dos eventos do Senhor dos Anéis.',
                'quantidade_disponivel' => 7,
                'acao' => 'editou',
                'responsavel_mov' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'A Revolução dos Bichos',
                'autor' => 'George Orwell',
                'genero_id' => 1,
                'descricao_livro' => 'Fábula política que critica regimes totalitários.',
                'quantidade_disponivel' => 5,
                'acao' => 'adicionou',
                'responsavel_mov' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Caçador de Pipas',
                'autor' => 'Khaled Hosseini',
                'genero_id' => 2,
                'descricao_livro' => 'História de amizade, traição e redenção no Afeganistão.',
                'quantidade_disponivel' => 8,
                'acao' => 'removeu',
                'responsavel_mov' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Silmarillion',
                'autor' => 'J.R.R. Tolkien',
                'genero_id' => 3,
                'descricao_livro' => 'Histórias da criação e mitologia da Terra Média.',
                'quantidade_disponivel' => 4,
                'acao' => 'editou',
                'responsavel_mov' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Inferno',
                'autor' => 'Dan Brown',
                'genero_id' => 4,
                'descricao_livro' => 'Thriller sobre segredos ocultos em obras de arte famosas.',
                'quantidade_disponivel' => 7,
                'acao' => 'adicionou',
                'responsavel_mov' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Poder do Hábito',
                'autor' => 'Charles Duhigg',
                'genero_id' => 7,
                'descricao_livro' => 'Análise sobre como hábitos influenciam a vida e negócios.',
                'quantidade_disponivel' => 9,
                'acao' => 'removeu',
                'responsavel_mov' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'A Brief History of Time',
                'autor' => 'Stephen Hawking',
                'genero_id' => 8,
                'descricao_livro' => 'Discussões sobre o espaço, tempo e o universo.',
                'quantidade_disponivel' => 5,
                'acao' => 'editou',
                'responsavel_mov' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
    
        ]);
    }
}
