<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LivroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //id	titulo	autor	genero_id	quantidade_disponivel	acao	responsavel_mov	created_at	updated_at	
        DB::table('livro')->insert([
            [
                'titulo' => 'O Senhor dos Anéis',
                'autor' => 'J.R.R. Tolkien',
                'genero_id' => 3,
                'quantidade_disponivel' => 5,
                'acao' => 'disponível',
                'responsavel_mov' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Dom Casmurro',
                'autor' => 'Machado de Assis',
                'genero_id' => 2,
                'quantidade_disponivel' => 4,
                'acao' => 'disponível',
                'responsavel_mov' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => '1984',
                'autor' => 'George Orwell',
                'genero_id' => 1,
                'quantidade_disponivel' => 7,
                'acao' => 'disponível',
                'responsavel_mov' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Código Da Vinci',
                'autor' => 'Dan Brown',
                'genero_id' => 4,
                'quantidade_disponivel' => 6,
                'acao' => 'disponível',
                'responsavel_mov' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'A Guerra dos Tronos',
                'autor' => 'George R.R. Martin',
                'genero_id' => 3,
                'quantidade_disponivel' => 3,
                'acao' => 'disponível',
                'responsavel_mov' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Pequeno Príncipe',
                'autor' => 'Antoine de Saint-Exupéry',
                'genero_id' => 1,
                'quantidade_disponivel' => 8,
                'acao' => 'disponível',
                'responsavel_mov' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Orgulho e Preconceito',
                'autor' => 'Jane Austen',
                'genero_id' => 2,
                'quantidade_disponivel' => 5,
                'acao' => 'disponível',
                'responsavel_mov' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'A Menina que Roubava Livros',
                'autor' => 'Markus Zusak',
                'genero_id' => 4,
                'quantidade_disponivel' => 6,
                'acao' => 'disponível',
                'responsavel_mov' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Sapiens',
                'autor' => 'Yuval Noah Harari',
                'genero_id' => 8,
                'quantidade_disponivel' => 9,
                'acao' => 'disponível',
                'responsavel_mov' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Diário de Anne Frank',
                'autor' => 'Anne Frank',
                'genero_id' => 6,
                'quantidade_disponivel' => 4,
                'acao' => 'disponível',
                'responsavel_mov' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Como Fazer Amigos e Influenciar Pessoas',
                'autor' => 'Dale Carnegie',
                'genero_id' => 7,
                'quantidade_disponivel' => 10,
                'acao' => 'disponível',
                'responsavel_mov' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Universo numa Casca de Noz',
                'autor' => 'Stephen Hawking',
                'genero_id' => 8,
                'quantidade_disponivel' => 5,
                'acao' => 'disponível',
                'responsavel_mov' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Cem Anos de Solidão',
                'autor' => 'Gabriel García Márquez',
                'genero_id' => 1,
                'quantidade_disponivel' => 6,
                'acao' => 'disponível',
                'responsavel_mov' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Hobbit',
                'autor' => 'J.R.R. Tolkien',
                'genero_id' => 3,
                'quantidade_disponivel' => 7,
                'acao' => 'disponível',
                'responsavel_mov' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'A Revolução dos Bichos',
                'autor' => 'George Orwell',
                'genero_id' => 1,
                'quantidade_disponivel' => 5,
                'acao' => 'disponível',
                'responsavel_mov' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Caçador de Pipas',
                'autor' => 'Khaled Hosseini',
                'genero_id' => 2,
                'quantidade_disponivel' => 8,
                'acao' => 'disponível',
                'responsavel_mov' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Silmarillion',
                'autor' => 'J.R.R. Tolkien',
                'genero_id' => 3,
                'quantidade_disponivel' => 4,
                'acao' => 'disponível',
                'responsavel_mov' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Inferno',
                'autor' => 'Dan Brown',
                'genero_id' => 4,
                'quantidade_disponivel' => 7,
                'acao' => 'disponível',
                'responsavel_mov' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'O Poder do Hábito',
                'autor' => 'Charles Duhigg',
                'genero_id' => 7,
                'quantidade_disponivel' => 9,
                'acao' => 'disponível',
                'responsavel_mov' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'A Brief History of Time',
                'autor' => 'Stephen Hawking',
                'genero_id' => 8,
                'quantidade_disponivel' => 5,
                'acao' => 'disponível',
                'responsavel_mov' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],    
        ]);
    }
}
